# Generated by Django 5.0 on 2025-12-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='gestorCursos.curso'),
        ),
    ]
