# Generated by Django 5.0 on 2025-12-01 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorCursos', '0002_alumno_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='cursos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestorCursos.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
